name: Gemfile.lock Change Detection

on:
  push:
    paths:
      - '**/Gemfile.lock'
  pull_request:
    paths:
      - '**/Gemfile.lock'

permissions:
  contents: write

jobs:
  analyze-gemfile-lock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the entire history to resolve PR changes

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install semgrep via pip
      run: |
        python -m pip install --upgrade pip
        pip install semgrep==1.55.0

    - name: Make directory for old and new Gemfile.lock
      run: |
        mkdir -p /tmp/Gemfile

    - name: Identify and copy the old and new Gemfile.lock
      run: |
        cp test_app/Gemfile.lock /tmp/Gemfile.lock.new
        git checkout "$BASE_SHA"
        cp test_app/Gemfile.lock /tmp/Gemfile.lock.old
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}

    - name: Clone the whiskers repository
      run: |
        git clone https://github.com/ancat/whiskers.git /tmp/whiskers

    - name: Run lockfile_diff and gem_diff_bulk
      run: |
        cd /tmp/whiskers
        bin/whiskers lockfile_diff --json --old /tmp/Gemfile.lock.old --new /tmp/Gemfile.lock.new > /tmp/gemfile_changes.json
        bin/whiskers gem_diff_bulk --input /tmp/gemfile_changes.json > /tmp/gemfile_diff_output.txt

    - name: Create Comment
      run: |
        # Use GitHub API to create a comment on the PR
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT='```'"$(cat /tmp/gemfile_changes.json)"'```'
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
